version: '2.1'

services:


  #service 1: Authentication service
  authService:
    image: auth-service
    container_name: auth-service
    hostname: auth-service
    build :
      context : ./AuthServer
      dockerfile: Dockerfile
    expose:
      - "8090"
    environment:
      transaction-service_get-transactions-url : transactionservice:8050/api/transactions/getTransactionsByAccountNumber
      transaction-service_get-balance-url : transactionservice:8050/api/transactions/getBalanceByAccountNumber
      transaction-service_new-transaction-queue : transaction
      spring_rabbitmq_addresses : amqp://account_service:1234@rabbitmq/banking
    restart: always

  #service 2: Product service
  productService:
    image: product-service
    container_name: product-service
    hostname: product-service
    build:
      context: ./productService
      dockerfile: Dockerfile
    expose:
      - "8084"
    restart: always
  #service 3: API Gateway
  apiGateway:
    image: apigateway
    container_name: apigateway
    hostname: apigateway
    build :
      context : ./ApiGateWay
      dockerfile: Dockerfile
    ports:
      - '8010:8010'
    environment:
      transaction-service_new-transaction-queue : transaction
      spring_rabbitmq_addresses : amqp://transaction_service:1234@rabbitmq/banking
    restart: always
    depends_on:
      - authService
      - productService