version: '2.1'

services:

  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "6379"
  #service 1: Authentication service
  authService:
    image: auth-service
    container_name: auth-service
    hostname: auth-service
    build :
      context : ./AuthServer
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      jwt_secret : ${JWT_KEY}
    restart: always

  #service 2: Product service
  productService:
    image: product-service
    container_name: product-service
    hostname: product-service
    build:
      context: ./productService
      dockerfile: Dockerfile
    expose:
      - "8084"
    environment:
      jwt_secret : ${JWT_KEY}
    restart: always
  #service 3: API Gateway
  apiGateway:
    image: apigateway
    container_name: apigateway
    hostname: apigateway
    build :
      context : ./ApiGateWay
      dockerfile: Dockerfile
    ports:
      - '8010:8010'
    environment:
         jwt_secret : ${JWT_KEY}
    restart: always
    depends_on:
      - authService
      - productService