
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

server:
  port: 8010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=0
        - id: auth-service
          uri: http://localhost:8080 #authService
          predicates:
            - Path=/auth/**
          filters :
            - StripPrefix=0

