
jwt:
  secretKey: ${JWT_KEY}

server:
  port: 8010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://productService:8084
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=0
        - id: auth-service
          uri: http://authService:8080 #
          predicates:
            - Path=/auth/**
          filters :
            - StripPrefix=0

